import { RANDOM_BYTES_VALUE, WORKER_POOL_ENABLED } from '../config';
import { poolProxy } from '../workers';
import { generateRandomBytes } from './generateRandomBytes';

const autoGeneratedRandomToken = async () => {
  const randomToken = await (WORKER_POOL_ENABLED === '1'
    ? poolProxy.generateRandomBytesWorker(RANDOM_BYTES_VALUE)
    : generateRandomBytes(RANDOM_BYTES_VALUE));
  return randomToken;
};

export { autoGeneratedRandomToken };
