export * from './api/v1/bookingsRouter';
export * from './api/v1/prismaRouter';
export * from './api/v1/reviewRouter';
export * from './api/v1/staticsRouter';
export * from './api/v1/toursRouter';
export * from './api/v1/usersRouter';
export * from './api/v1/viewsRouter';
export * from './errorsRouter';
// export * from './unsupportedMethodRouter';
// export * from './fibonacci';
// export * from './root';
// export * from './send';
